### ISSUE TITLE
FYI (ter info)

### ISSUE THREAD

**Issue by waldenn** [joppiesaus/zombie#1]
Hey,

I think I found a good game architecture setup + physics solution. Have a look at the "Game Design I" tile here:  http://spirare.js.org/app/#game-programming

Working physics based on Cannon.js: http://spirare.js.org/app/examples/game-frame/demo4_aync_models.html

We can start building real games with this setup I think. See you next week!

**Comment by joppiesaus** [comment]
'til next week!
